name: riders_food_app
description: MotoJoe Rider App

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase
  firebase_core: ^2.25.0
  firebase_auth: ^5.2.0
  firebase_database: ^10.2.0
  cloud_firestore: ^5.4.0

  # State Management
  provider: ^6.1.4

  # Google Maps
  google_maps_flutter: ^2.5.0

  # Image Picker
  image_picker: ^1.0.7

  # Localization
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - ss/
    - assets/fonts/
    - web/icons/
    - web/
