name: riders_food_app
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.20.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2

  # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.2
  firebase_database: ^11.3.10
  cloud_firestore: ^5.4.0

  # State management
  provider: ^6.1.4

  # خرائط ومواقع
  google_maps_flutter: ^2.5.0

  # اختيار الصور
  image_picker: ^1.0.7

  # الترجمة والدعم المحلي
  flutter_localizations:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - images/
    - ss/
    - assets/fonts/
    - web/icons/
    - web/
